spring.application.name=report-service
server.port=${REPORT_SERVICE_PORT:8083}

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.datasource.url=${REPORT_SERVICE_DB:jdbc:mysql://localhost:3306/reports_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${REPORT_SERVICE_DB_USERNAME:root}
spring.datasource.password=${REPORT_SERVICE_DB_PASSWORD:Tamaulipas69}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

spring.rabbitmq.host=${RABBIT_HOST:localhost}
spring.rabbitmq.port=${RABBIT_PORT:5672}
spring.rabbitmq.username=${RABBIT_USERNAME:guest}
spring.rabbitmq.password=${RABBIT_PASSWORD:guest}

app.broker.exchange.report=report.exchange
app.broker.routing-key.report.created=report.created
app.broker.routing-key.report.approved=report.approved
app.broker.routing-key.report.rejected=report.rejected
app.broker.routing-key.report.deleted=report.deleted
app.broker.queue.report.created=report.created.queue
app.broker.queue.report.approved=report.approved.queue
app.broker.queue.report.rejected=report.rejected.queue
app.broker.queue.report.deleted=report.deleted.queue
